apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-server-pvc
  namespace: utils
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: git-server-pv
