apiVersion: v1
kind: Service
metadata:
  labels:
    app: git-server
    tier: server
  name: svc-git-server
  namespace: utils
spec:
  ports:
  - name: http
    nodePort: 30005
    port: 22
    protocol: TCP
  selector:
    app: git-server
    tier: server
  type: NodePort
